#monitor_incidencia:
#    resource: "@MonitorBundle/Resources/config/routing/incidencia.yml"
#    prefix:   /incidencia
#
#monitor_homepage:
#    path:     /
#    defaults: { _controller: MonitorBundle:Default:index }
    
root:
    path:     /
    defaults: 
        _controller: FrameworkBundle:Redirect:Redirect
        route: fos_user_security_login
        permanent: true

incidencia_index:
    path:     /
    defaults: { _controller: "MonitorBundle:Incidencia:index" }
    methods:  GET

incidencia_show:
    path:     /{id}/show
    defaults: { _controller: "MonitorBundle:Incidencia:show" }
    methods:  GET

incidencia_new:
    path:     /new
    defaults: { _controller: "MonitorBundle:Incidencia:new" }
    methods:  [GET, POST]

incidencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "MonitorBundle:Incidencia:edit" }
    methods:  [GET, POST]

incidencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "MonitorBundle:Incidencia:delete" }
    methods:  DELETE
    
#servicio_check:
#    path:     /servicio/check
#    defaults: { _controller: "MonitorBundle:Servicio:check" }
#    methods:  [POST]    
#
#servicio_body:
#    path:   /servicio/body
#    defaults: { _controller: "MonitorBundle:Servicio:body" }
#    methods:  [GET]    
#    
#servicio_assign:
#    path:   /{id}/assign
#    defaults: { _controller: "MonitorBundle:Servicio:assign" }
#    methods:  [GET,POST]        
#    
#servicio_finish:
#    path:   /{id}/finish
#    defaults: { _controller: "MonitorBundle:Servicio:finish" }
#    methods:  [GET,POST]    
#    
#servicio_desa:
#    path:   /{id}/desa
#    defaults: { _controller: "MonitorBundle:Servicio:desa" }
#    methods:  [GET,POST]      
#    
#servicio_test:
#    path:   /{id}/test
#    defaults: { _controller: "MonitorBundle:Servicio:test" }
#    methods:  [GET,POST]      
#    
#servicio_pap:
#    path:   /{id}/pap
#    defaults: { _controller: "MonitorBundle:Servicio:pap" }
#    methods:  [GET,POST]   
#    
#servicio_complete:
#    path:   /complete
#    defaults: { _controller: "MonitorBundle:Servicio:complete" }
#    methods:  [GET,POST]      
#
#dashboard_index:
#    path:  /dashboard
#    defaults: { _controller: "MonitorBundle:Dashboard:index" } 
#    methods:  [GET,POST]     
