#monitor_incidencia:
#    resource: "@MonitorBundle/Resources/config/routing/incidencia.yml"
#    prefix:   /incidencia
#
#monitor_homepage:
#    path:     /
#    defaults: { _controller: MonitorBundle:Default:index }
    
root:
    path:     /
    defaults: 
        _controller: FrameworkBundle:Redirect:Redirect
        route: fos_user_security_login
        permanent: true

incidencia_index:
    path:     /incidencia
    defaults: { _controller: "MonitorBundle:Incidencia:index" }
    methods:  [GET,POST]

incidencia_show:
    path:     /incidencia/{id}/show
    defaults: { _controller: "MonitorBundle:Incidencia:show" }
    methods:  GET

incidencia_new:
    path:     /incidencia/new
    defaults: { _controller: "MonitorBundle:Incidencia:new" }
    methods:  [GET, POST]

incidencia_edit:
    path:     /incidencia/{id}/edit
    defaults: { _controller: "MonitorBundle:Incidencia:edit" }
    methods:  [GET, POST]

incidencia_delete:
    path:     /incidencia/{id}/delete
    defaults: { _controller: "MonitorBundle:Incidencia:delete" }
    methods:  DELETE
    
incidencia_check:
    path:     /incidencia/check
    defaults: { _controller: "MonitorBundle:Incidencia:check" }
    methods:  [POST]    

incidencia_body:
    path:   /incidencia/body
    defaults: { _controller: "MonitorBundle:Incidencia:body" }
    methods:  [GET]    
    
incidencia_status:    
    path:   /incidencia/{id}/{status}/{usuario}/{observacion}/status
    defaults: { _controller: "MonitorBundle:Incidencia:status" }
    methods:  [GET,POST]            
    
incidencia_mantencion:
    path:   /incidencia/{id}/mantencion
    defaults: { _controller: "MonitorBundle:Incidencia:mantencion" }
    methods:  [GET,POST]                
    
incidencia_historial:
    path:     /incidencia/historial
    defaults: { _controller: "MonitorBundle:Incidencia:historial" }
    methods:  [GET,POST]       
    
incidencia_comentario:
    path:     /incidencia/comentario
    defaults: { _controller: "MonitorBundle:Incidencia:comentario" }
    methods:  [GET,POST]     
    
mantencion_index:
    path:     /mantencion
    defaults: { _controller: "MonitorBundle:Mantencion:index" }
    methods:  GET

mantencion_show:
    path:     /mantencion/{id}/show
    defaults: { _controller: "MonitorBundle:Mantencion:show" }
    methods:  GET
    
mantencion_body:
    path:   /mantencion/body
    defaults: { _controller: "MonitorBundle:Mantencion:body" }
    methods:  [GET]        

mantencion_new:
    path:     /mantencion/new
    defaults: { _controller: "MonitorBundle:Mantencion:new" }
    methods:  [GET, POST]

mantencion_edit:
    path:     /mantencion/{id}/edit
    defaults: { _controller: "MonitorBundle:Mantencion:edit" }
    methods:  [GET, POST]

mantencion_delete:
    path:     /mantencion/{id}/delete
    defaults: { _controller: "MonitorBundle:Mantencion:delete" }
    methods:  DELETE    
    
mantencion_check:
    path:     /mantencion/check
    defaults: { _controller: "MonitorBundle:Mantencion:check" }
    methods:  [POST]        
    
mantencion_check2:
    path:     /mantencion/check2
    defaults: { _controller: "MonitorBundle:Mantencion:check2" }
    methods:  [POST]        
    
mantencion_check3:
    path:     /mantencion/check3
    defaults: { _controller: "MonitorBundle:Mantencion:check3" }
    methods:  [POST]      
    
mantencion_status:    
    path:   /mantencion/{id}/{status}/{usuario}/{observacion}/status
    defaults: { _controller: "MonitorBundle:Mantencion:status" }
    methods:  [GET,POST]      

mantencion_cerrar:    
    path:   /mantencion/{componente}/{mes}/{anio}/cerrar
    defaults: { _controller: "MonitorBundle:Mantencion:cerrar" }
    methods:  [GET,POST]      
    
mantencion_historial:
    path:     /mantencion/historial
    defaults: { _controller: "MonitorBundle:Mantencion:historial" }
    methods:  [GET,POST]       
    
mantencion_comentario:
    path:     /mantencion/comentario
    defaults: { _controller: "MonitorBundle:Mantencion:comentario" }
    methods:  [GET,POST]        
    
dashboard_index:
    path:  /dashboard
    defaults: { _controller: "MonitorBundle:Dashboard:index" } 
    methods:  [GET,POST]     
