services:
#    monitor.example:
#        class: Fonasa\MonitorBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    monsis.authentication.login_success_handler:
        class:  Fonasa\MonitorBundle\EventListener\LoginSuccessHandler
        arguments:  ["@router", "@security.authorization_checker", "@security.token_storage"]
    monsis.authentication.logout_handler:
        class:  Fonasa\MonitorBundle\EventListener\LogoutHandler
        arguments:  []
    monsis.request_listener:
        class: Fonasa\MonitorBundle\EventListener\RequestListener
        arguments: ["@router", "@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }        
    monsis.response_listener:
        class: Fonasa\MonitorBundle\EventListener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse  }   
    monsis.controller_listener:
         class: Fonasa\MonitorBundle\EventListener\ControllerListener
         arguments: ["@router", "@security.authorization_checker", "@security.token_storage", "@session"]
         tags:	
             - { name: kernel.event_listener, event: kernel.controller, method: onKernelController  }		                    
    monsis.helper.filters:
        class:  Fonasa\MonitorBundle\Helper\FiltersHelper
        arguments: ["@form.factory", "@doctrine.orm.entity_manager", "@session", "@service_container"]
    monsis.twig.GlobalFiltersExtension:
        class: Fonasa\MonitorBundle\Twig\GlobalFiltersExtension
        arguments:  ["@service_container"]
        tags:
            - { name: twig.extension }             
            