<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * CategoriaMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
