<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * CategoriaIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
