<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * ComentarioMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
