<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * ComentarioIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
