<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * DocumentoMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
