<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * DocumentoIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
