<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * EstadoIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
