<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * EstadoMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
