<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * HhMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HhMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
