<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * HistorialMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
