<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * HistorialIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
