<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * MantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
