<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * ObservacionIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
