<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * OrigenIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
