<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * OrigenMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigenMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
