<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * RequerimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
