<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * SeveridadMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeveridadMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
