<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * SeveridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeveridadRepository extends \Doctrine\ORM\EntityRepository
{
}
