<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * TipoDocumentoMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentoMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
