<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * TipoDocumentoIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocumentoIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
