<?php

namespace Fonasa\MonitorBundle\Repository;

/**
 * TipoMantencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMantencionRepository extends \Doctrine\ORM\EntityRepository
{
}
